### ISSUE TITLE
Pararsolid version

### ISSUE THREAD

**Issue by danwhale** [deGravity/hybridbrep#1]
Hi, thank you for an amazing work. Could you extend the README.md by providing appropriate version of Parasolid?

**Comment by deGravity** [comment]
There's no specific version of parasolid this is tied to. In fact, I have recently updated the breploader package this depends on to be installable without parasolid, so you should be able to install and run it using just OpenCascade. If you want to use parasolid, you can follow the instructions on the [automate readme](https://github.com/deGravity/automate) that explain how to set up environmental variables to point at your parasolid install.
